### PR TITLE
Make max page size per pull configurable

### PR DESCRIPTION
**Pull request by ramSeraph**
Had to edit it manually the couple of times I used the tool. I think this should be configurable.

### CODE REVIEW

**Comment by ramSeraph** [comment]
related to #84

**Comment by iandees** [comment]
Thanks!

**Comment by ramSeraph** [comment]
Looks like there are test failures.. I will check.

**Comment by ramSeraph** [comment]
Adding this diff fixed it
```diff
diff --git a/tests/test_cli.py b/tests/test_cli.py
index 24ca14e..1ccf93b 100644
--- a/tests/test_cli.py
+++ b/tests/test_cli.py
@@ -57,6 +57,7 @@ class TestEsriDumpCommandlineMain(unittest.TestCase):
         self.parse_return = mock.MagicMock()
         self.parse_return.url = 'http://example.com'
         self.parse_return.outfile = self.mock_outfile
+        self.parse_return.max_page_size = 1000
         self.parse_return.loglevel = logging.ERROR
         self.parse_return.jsonlines = False
         self.parse_return.fields = None
```

Do I need to make a new pull request? I am kind of new to the PR workflow

**Comment by iandees** [comment]
Sure, if you want to file another pull request that would be helpful. I should have caught it earlier - it looks like the tests didn't run on your pull request.

**Comment by ramSeraph** [comment]
Created new PR at #90 

I should have run the tests beforehand too :(

**Pull request merged**
